default: &default
  username: hexlet
  adapter: mysql2
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: hexlet_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
